# ===================================================================
# 'dev' 프로필 전용 설정 (개발 환경)
# ===================================================================
spring:
  # ===================================================================
  # 데이터 소스 설정 (H2 In-Memory DataSource)
  # ===================================================================
  datasource:
    url: jdbc:h2:mem:devdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # ===================================================================
  # JPA 및 Hibernate 설정
  # ===================================================================
  jpa:
    show-sql: false # SQL 쿼리 로그 출력 비활성화
    hibernate:
      ddl-auto: create # 애플리케이션 시작 시 스키마를 새로 생성
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect # H2 데이터베이스 방언 사용
        format_sql: true # SQL을 보기 좋게 포맷팅

  # ===================================================================
  # H2 데이터베이스 콘솔 설정
  # ===================================================================
  h2:
    console:
      enabled: true # H2 콘솔 활성화
      path: /h2-console # H2 콘솔 접속 경로

# ===================================================================
# 암호화 설정 (Encryption Configuration for Dev)
# ===================================================================
encryption:
  # 개발용 암호화 시크릿 키 (32자)
  secret-key: dev-encryption-secret-key-for32

# ===================================================================
# 로깅 설정 (개발 환경에 맞게 상세 설정)
# ===================================================================
logging:
  level:
    S13P31A306.loglens: TRACE
    org.hibernate.SQL: ERROR # Hibernate가 실행하는 SQL 로그 출력
    org.hibernate.type.descriptor.sql: ERROR # SQL 바인딩 파라미터 로그 출력
    org.springframework.security: DEBUG


dependency:
  logger:
    api-key: 48d96cd7-bf8d-38f5-891c-9c2f6430d871

    collector:
      url: https://api.loglens.co.kr
    enabled: true

    stacktrace:
      max-lines: 3
