global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'fintech-osm-app'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['127.0.0.1:18080']
        labels:
          app: 'fintech-osm'
          env: 'production'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
